name: Help
description: File a question for help.
title: "[Help] "
labels: ["help wanted"]
body:
  - type: markdown
    attributes:
      value: |
        If no other issue template fits please use this.
  - type: textarea
    id: help
    attributes:
      label: I need Help.
      description: Describe the current situation and state your question.
      placeholder: Write at least three sentences and be as precise as possible. **Provide all necessary information** to be able to **reproduce** your case / what you try to describe. Otherwise this issue will be closed!
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: What operating system are you seeing the problem on?
      multiple: false
      options:
        - macOS
        - Linux
        - Windows
  - type: textarea
    id: config
    attributes:
      label: Your settings
      description: Please copy and paste your settings from `~/.config/tidal_dl_ng/settings.json` (macOS & Linux) / `%HOMEPATH%\.config\tidal_dl_ng\settings.json` (Windows). This will be automatically formatted into code, so no need for backticks.
      render: json
    validations:
      required: true
